ame: Bi daily Scheduled Script Execution

on:
  schedule:
    - cron: "0 16 * * *"
    - cron: "0 4 * * *"

jobs:
  run-grab-script:
    runs-on: ubuntu-latest

    steps:

    - name: Set up R
      uses: r-lib/actions/setup-r@v2


    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::tidyverse
          any::httr
          any::rvest
          any::tidyr
          any::here
          any::httr2
          any::purrr
          any::arrow

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run bidaily_grab.R
      run: Rscript -e 'source("dashboard/bidaily_grab.R")'

    - name: Commit and push changes
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name 'Github Actions'
        git add data_backup/upper_CLP_WQ_data_2025.parquet
        git commit -m "Update parquet file after bi daily pull"
        git push origin
